# Generated by Django 4.2.3 on 2023-07-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateField(default='2023-07-12'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
