# Generated by Django 4.2.3 on 2023-07-12 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 9, 51, 33, 71327)),
        ),
    ]
